spring:
  profiles:
    active: local
  mongodb:
    host: localhost
    port: 27017
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      port: 27017

---
logging:
  level:
    root: info